baseURL = 'https://yiquanfeng.github.io/'
languageCode = 'en-us'
title = "Spriple's Blog"
theme = 'typo'

[params]
description = "A web"

paginationSize = 100

homeCollectionTitle = 'Posts'
homeCollection = 'posts'

[[params.menu]]
name = "about"
url = "/about"